###GET users
GET http://localhost:3000/users

###POST users
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "diegoabox@gmail.com",
    "password": "123456",
    "name": "Diegão Emanuel"
}


###PUT users
PUT http://localhost:3000/users/beab14b1-ed81-4e5e-92b2-eb5a249bc055
Content-Type: application/json

{
    "name": "Diego Emanuel"
}

###DELETE users
DELETE http://localhost:3000/users/1

###DELETE all users
DELETE http://localhost:3000/users

###Delete all users
DELETE http://localhost:3000/users/


