###GET users
DELETE http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOWRiYjg4Zi0zYWZjLTRkMjItYjEwMi05NGU4OGI3ZTMwYTgiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk3NTE4NzAsImV4cCI6MTczOTc1NTQ3MH0.RAZ1Hesk4xUGc3W8fEzkI2oM5FhSDiRUs5u0T9ZboYo


###GET users render
GET https://teste-tecnico-syno-api.onrender.com/
Content-Type: application/json


###POST users
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "diegoabox@gmail.com",
    "password": "123456",
    "name": "Diegão Emanuel"
}


###PUT users
PUT http://localhost:3000/users/beab14b1-ed81-4e5e-92b2-eb5a249bc055
Content-Type: application/json

{
    "name": "Diego Emanuel FC"
}

###DELETE users
DELETE http://localhost:3000/users/70b0684b-977b-4232-a08c-113c0e6b6dd

###DELETE all users
DELETE http://localhost:3000/users

###Delete all users
DELETE http://localhost:3000/users/


