###login
POST https://teste-tecnico-syno-api.onrender.com/users
Content-Type: application/json

{
    "email": "diegoabox@gmail.com",
    "password": "123456"
}


###verify token vazio
GET http://localhost:3000/users/verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGIwNjg0Yi05NzdiLTQyMzItYTA4Yy0xMTNjMGU2YjZkZDIiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk0Nzc1NzksImV4cCI6MTczOTQ4MTE3OX0.YKn6UOlG74enr-45YmXyUz-EtdfZlCPKhvT8YECyKTw
###verify token
GET https://teste-tecnico-syno-api.onrender.com/users/verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGIwNjg0Yi05NzdiLTQyMzItYTA4Yy0xMTNjMGU2YjZkZDIiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk0Nzc1NzksImV4cCI6MTczOTQ4MTE3OX0.YKn6UOlG74enr-45YmXyUz-EtdfZlCPKhvT8YECyKTw


###delete all users sem token
DELETE http://localhost:3000/users


###delete all users com token
DELETE http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGIwNjg0Yi05NzdiLTQyMzItYTA4Yy0xMTNjMGU2YjZkZDIiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3MzkzOTkwNTUsImV4cCI6MTczOTQwMjY1NX0.DVbj9QjWwIh2H4KSXrHLpCxI1xuVnDnyEbGn5FZF2bY











