###GET
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGIwNjg0Yi05NzdiLTQyMzItYTA4Yy0xMTNjMGU2YjZkZDIiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk1NDIzNTYsImV4cCI6MTczOTU0NTk1Nn0.YX_MI-utfgQk7cn5m4_fvsexCZecbMzsuUnfs4fBcIs

###POST
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOWRiYjg4Zi0zYWZjLTRkMjItYjEwMi05NGU4OGI3ZTMwYTgiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk2Mjg2NDEsImV4cCI6MTczOTYzMjI0MX0.57GozFrbNjWWWzbLHKvJ8uOavX74RIyM39BA6nFSBYs

{
    "codigo_produto": "09",
    "descricao_produto": "Produto de teste",
    "status": true
}

###PUT
PUT http://localhost:3000/products/074447c5-4096-44e3-98fe-245724f28080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOWRiYjg4Zi0zYWZjLTRkMjItYjEwMi05NGU4OGI3ZTMwYTgiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk2Mjg2NDEsImV4cCI6MTczOTYzMjI0MX0.57GozFrbNjWWWzbLHKvJ8uOavX74RIyM39BA6nFSBYs

 {
    "codigo_produto": "3",
    "descricao_produto": "Produto de teste",
    "status": true,
    "foto_produto": "https://avatars.githubusercontent.com/u/43099313?v=4"
  }
###DELETE
DELETE http://localhost:3000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOWRiYjg4Zi0zYWZjLTRkMjItYjEwMi05NGU4OGI3ZTMwYTgiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk2NjA0NTgsImV4cCI6MTczOTY2NDA1OH0.xkznTDS2DQSwJH0-VNarW8Il1J_rGtfjsJVlqjpe49w



###UPDATE STATUS
PUT http://localhost:3000/products/7d116f2e-a551-4b98-91f6-b988be354094
Content-Type: application/json

{
    "status": true
}


###GET BY ID
GET http://localhost:3000/products/9269415b-0afb-4146-b067-85dce66fe980
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGIwNjg0Yi05NzdiLTQyMzItYTA4Yy0xMTNjMGU2YjZkZDIiLCJlbWFpbCI6ImRpZWdvYWJveEBnbWFpbC5jb20iLCJpYXQiOjE3Mzk0NzQyMTUsImV4cCI6MTczOTQ3NzgxNX0.lQQtWdrDp2_jNoWrVfNpoYeoSpqbOTm3CZfikhPriu8





