###GET
GET http://localhost:3000/products

###POST
POST http://localhost:3000/products
Content-Type: application/json

{
    "codigo_produto": "2",
    "descricao_produto": "Produto de teste",
    "foto_produto": "https://avatars.githubusercontent.com/u/43099313?v=4"
}

###PUT
PUT http://localhost:3000/products/7d116f2e-a551-4b98-91f6-b988be354094
Content-Type: application/json

{
    "status": false
}

###DELETE
DELETE http://localhost:3000/products/903ff487-a930-4a8e-a3f2-3b00f31ab7b3


###UPDATE STATUS
PUT http://localhost:3000/products/7d116f2e-a551-4b98-91f6-b988be354094
Content-Type: application/json

{
    "status": true
}









