name: Deploy Backend para Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

    #   - name: Deploy para Render
    #     env:
    #       RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    #     run: |
    #       curl -X POST \
    #         -H 'Accept: application/json' \
    #         -H 'Authorization: Bearer $RENDER_API_KEY' \
    #         -d '' \
    #         https://api.render.com/v1/services/SERVICE_ID/deploys
